- name: Record the number of groups
  set_fact:
    group_count: "{{ groups | length }}"

- name: setup couchdb cluster
  become: yes
  uri:
    url: http://{{ groups['master-server'][0] }}:5984/{{ cluster_name }}
    status_code: 201,409
    method: POST
    user: "{{ db_user }}"
    password:  "{{ db_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\",\
             \"username\": \"{{ db_user }}\", \"password\":\"{{ db_password }}\", \"port\": \"5984\",\
             \"remote_node\": \"{{ item }}\", \"node_count\": \"{{ group_count }}\",\
             \"remote_current_user\":\"{{ db_user }}\", \"remote_current_password\":\"{{ db_password }}\"}"
    headers:
      Content-Type: "application/json"
  loop: "{{ groups['all'] }}"


- name: setup couchdb cluster | step 2
  become: yes
  uri:
    url: http://{{ groups['master-server'][0] }}:{{db_port}}/{{ cluster_name }}
    status_code: 201
    method: POST
    force: yes
    user: "{{db_user }}"
    password:  "{{ db_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"add_node\", \"host\":\"{{ item }}\",\
             \"port\": \"{{ db_port }}\", \"username\": \"{{ db_user }}\", \"password\":\"{{ db_password }}\"}"
    headers:
      Content-Type: "application/json"
  loop: "{{ groups['all'] }}"
  ignore_errors: yes

- name: setup couchdb cluster | step 2.5
  become: yes
  uri:
    url: http://{{ groups['master-server'][0] }}:{{db_port}}/
    status_code: 200,201
    method: GET
    user: "{{ db_user }}"
    password:  "{{ db_password }}"
    force_basic_auth: yes
    return_content: yes


- name: steup couchdb cluster | step 3 -- finish
  become: yes
  uri:
    url: http://{{ groups['master-server'][0] }}:{{ db_port }}/{{ cluster_name }}
    status_code: 201
    method: POST
    user: "{{ db_user }}"
    password:  "{{ db_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"finish_cluster\"}"
    headers:
      Content-Type: "application/json"