- hosts: demo1
  vars_files:
    - host_vars/instance_var.yml
  gather_facts: true
  become: true

  tasks:
    - name: Install docker
      pip:
        name: docker-py

    - name: Create a network
      community.docker.docker_network:
        name: my-network

    - name: Deploy CouchDB
      docker_container:
        name: "{{db_name}}"
        image: couchdb
        pull: true
        state: started
        recreate: yes
        env:
          COUCHDB_USER: "{{db_user}}"
          COUCHDB_PASSWORD: "{{db_password}}"
        published_ports:
          - 5984:5984

