- hosts: localhost
  vars_files:
    - host_vars/instance_var.yml
    - host_vars/vars.yml
  gather_facts: true
  roles:
    #- role: common
    #- role: create_security_group
    #- role: create_volumes
    - role: create_instance
