
- hosts: workers
  vars_files:
    - host_vars/instance_var.yml
  become: true

  tasks:
  - name: Load CouchDB image
    docker_image:
      name: couchdb
      source: pull

  - name: Start CouchDB container
    docker_container:
      name: couch-node
      image: couchdb
      state: started
      volumes:
        - /data/couchdb:/opt/couchdb/data
      env:
        COUCHDB_USER: "{{ db_user }}"
        COUCHDB_PASSWORD: "{{ db_password }}"
        COUCHDB_SECRET: "{{ db_secret }}"
        ERL_FLAGS: "-setcookie '{{ db_secret }}' -name 'couchdb@{{ inventory_hostname }}'"
      ports:
        - "5984:5984"
        - "5986:5986"
        - "4369:4369"
#        - "9100-9150:9100-9150"
  - name: debug
    debug:
      var: "{{inventory_hostname}}"
    when: inventory_hostname == groups['workers'][0]

  - name: Enable clustering on first node
    uri:
      url: "http://{{ db_user }}:{{ db_password }}@{{ groups['workers'][0] }}:5984/_cluster_setup"
      method: POST
      body_format: json
      body:
        action: "enable_cluster"
        bind_address: "0.0.0.0"
        username: "{{ db_user }}"
        password: "{{ db_password }}"
        node_count: "{{ groups['workers'] | length }}"
    when: inventory_hostname == groups['workers'][0]


  - name: Add nodes to cluster
    uri:
      url: "http://{{db_user }}:{{db_password }}@{{ groups['workers'][0] }}:5984/_cluster_setup"
      method: POST
      body_format: json
      body:
        action: "add_node"
        host: "{{ inventory_hostname }}"
        port: "5984"
        username: "{{ db_user }}"
        password: "{{ db_password }}"
      status_code: 201
    when: inventory_hostname != groups['workers'][0]
