- hosts: backend-server
  vars_files:
    - host_vars/instance_var.yml
  gather_facts: true
  roles:
    - role: Install_depend

- hosts: master-server
  vars_files:
   - host_vars/instance_var.yml
  gather_facts: true
  roles:
    - role: Install_depend

- hosts: data-server
  vars_files:
    - host_vars/instance_var.yml
  gather_facts: true
  roles:
    - role: Install_depend

- hosts: frontend-server
  vars_files:
    - host_vars/instance_var.yml
  gather_facts: true
  roles:
    - role: Install_depend

#[backend-server]
#172.26.136.141
#
#[data-server]
#172.26.133.96
#
#[master-server]
#172.26.131.235