- name: Update apt cache
  become: True
  apt:
    update_cache: yes

- name: Install dependents
  become: True
  apt:
    name:
      - git
      - python3
      - docker.io
      - python3-pip
    state: present
#install docker, for create a network
- name: Install docker
  become: True
  pip:
    name: docker

#- name: Install docker
#  become: True
#  pip:
#    name: docker-py
#
