# Install dependencies on the localhost
- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  pip:
    name: ['pip']
    state: latest
- name: Install openstacksdk
  pip:
    name: ['openstacksdk==0.52']
    state: latest