
security_groups:
  - name: ssh
    description: "SSH access security_group"
    proto: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: " HTTP security group"
    proto: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb
    description: " couchdb security group "
    proto: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

  - name: other_couchdb
    description: "Security group for couchdb more port"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0

#  - name: couchdb-addition
#    description: "Security group for couchdb addition port"
#    proto: tcp
#    port_range_min: 5986
#    port_range_max: 5986
#    remote_ip_prefix: 0.0.0.0/0
#  - name: couchdb-range
#    description: "Security group for couchdb range port"
#    proto: tcp
#    port_range_min: 9100
#    port_range_max: 9150
#    remote_ip_prefix: 0.0.0.0/0
#  - name: couchdb-more
#    description: "Security group for couchdb more port"
#    proto: tcp
#    port_range_min: 4369
#    port_range_max: 4369
#    remote_ip_prefix: 0.0.0.0/0
#  - name: server-port
#    description: "Additional backend server port"
#    proto: tcp
#    port_range_min: 8001
#    port_range_max: 8001
#    remote_ip_prefix: 0.0.0.0/0


instances:
  - name: backend-server
    security_groups: ['ssh', 'http', 'couchdb','other_couchdb']
  - name: data-server
    security_groups: ['ssh', 'http', 'couchdb','other_couchdb']
  - name: master-server
    security_groups: ['ssh', 'http','couchdb','other_couchdb']

availability_zone: melbourne-qh2-uom
instance_flavor: uom.mse.1c4g
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: demo
instance_network: qh2-uom-internal
root_path: /home/ubuntu
react_path:
django_path:
mastodon_path: /home/ubuntu/mastodon
ansible_user: ubuntu
my_mastodon_git_repo: git@github.com:Comp90024-group32/Mastodon.git
ansible_ssh_private_key_file: ~/.ssh/demo
#ansible_ssh_pass: junheng

db_user: admin
db_password: password
db_name: couchdb-container
db_image: couchdb
db_port: 5984
db_secret: "Hello world"


#cluster
cluster_name: "_cluster_setup"

#docker
docker_db: docker_couchdb